apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: citrix-node-controller-cred
spec:
  encryptedData:
    password: AgABKdBIeIvDFJVbO7ktbpYuiLYuYG0K9//MOhSCO9saLh6bMU3Rtl5uZrE7fiPTPj9VFvWC+slEh/wtzp7oDK7meevXrysJOfSoNkFseDpq7qn8NcqJJH46hJKIRtd88IkMTJ7+JQ1Drk/0oZyV+IXIYjS0K8BVr1JR/XOiyD9WQeWaIHUbxdyaJgh0XR1b9SkvjBAmSnPSsPQhxQluiR9Ivsyt5OUzbXSi15zaidFL2gIk7lEiS82p95ZuJo2qhJqsUT89D519iJL1D7W6fkjeogOvO06GalYyDSp14b3kkM8ht8xdNshH0Xkmul+o9bS603rwYCPxuTXTc0WrP/nYvxLK5we7ZswEiuacSwQDaDJx/17xqHZI5NOiaJkbowLc4xdxP4Iw0ag2alya9JUJ10lTu6SRx4RhNPebFpeUAYDgkkEB2dMek0Pt8iPyBNMqT65n/HQxqKhuaS1L00QTfaYZEGR71ZjnoP6rim3FyTKUuG9eBu1jbfV5j+lKBRXoW071fKvUJRg7EuoWMujVsWGDruQM4TSBwXmv9QPYHG1X5gI6NqPFo4Tvhk9vMzbeQEYkS8Jg4vOc8hG6gGnmz8iO8DPZKtSCSqsiTdd9Vc1xuacdzzXqU9QH2eh7A+A+2HsHfhimOSyteHIT3i3HLaBvPMw1BiXiQ4j/kvltTQ+oxfx85Jh9JhHI1eMJRm4X+SU2A6SXpa8Y3HMhYbrqbi7qt3B0YA==
    username: AgCQyyhCOMYaXRr8VncsPHNkzoKxvbHCtfNuf6P12yj1nBbI6hp7I2HuC2m+9VrhBdPCt/glRM+Odm4FSWfPwc8cABwZ4i/SMxcOVWqRCXjXTvkG2bimzayBVIEiHf/yXtD6TOJ8yDUUFn2cSecszkuM1/dtpNCR9PBclIYhdG+ybmZAoDDjMjKdy3mLYDNO121cFBv5dFkKw/A9oZLjzwL/3EvHU57Br2xxGfVEPvKP08d6qWysuDaBasv6PVAp5/spW3egpPH7QLQ6dpdrXOuBo5PPTFpqcAS5OvyCPkthL7dqlS97t2+gEf28/9AmhLbqByGT05uiiZalEaokjWheXUYuMWkTGdfigwi5TmRmG70/UCIENIpaQ/W+hCZmOfodRH3mvG/R3qgrbmiOyv9ieaSwm9MV5rS2ghs26FUb06pxmOPzW9g8fg6vBp8U1HodMnaCh47IW+cpmQj1CK6WMBZIOvurPxeCY0o7l+PgVlrgYKGDTKdfqPXs4PlpgHI5a7eLfYd34eCQ/lA9gegs7xFfmJvh/xM7E6GQEehWgO5iqukAdf4UHwsbKhfZRbMFR4zzVTTY05wKBYvqJWxwk0nKlji9oFr51AvVulvS3gIf2uHUUfZ45ajG+GzYUPeSYN35kkXbBTvqMJsfOrOyQCVlu+SqGcRA5kT1rP7M6Vi+3NIspLUFGUY38bto3XupNBBDoCathlBw
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: citrix-node-controller-cred
    type: Opaque
