defaultNamespace: buttahtoast-system
helm:
  chart: https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-12.8.1/kube-prometheus-stack-12.8.1.tgz
targetCustomizations:
- name: dev
  helm:
    values:
      alertmanager:
        ingress:
          enable: true
          hosts:
            - alertmanager-dev.intern.buttahtoast.ch
      grafana:
        ingress:
          enable: true
          hosts:
            - grafana-dev.intern.buttahtoast.ch
      prometheus:
        thanosIngress:
          enable: true
          hosts:
            - thanos-dev.intern.buttahtoast.ch
  clusterSelector:
    matchLabels:
      env: dev
      type: infra
- name: test
  helm:
    values:
      alertmanager:
        enable: true
        ingress:
          hosts:
            - alertmanager-test.intern.buttahtoast.ch
      grafana:
        ingress:
          enable: true
          hosts:
            - grafana-test.intern.buttahtoast.ch
      prometheus:
        thanosIngress:
          enable: true
          hosts:
            - thanos-test.intern.buttahtoast.ch
  clusterSelector:
    matchLabels:
      env: test
      type: infra
- name: prod
  helm:
    values:
      alertmanager:
        ingress:
          enable: true
          hosts:
            - alertmanager.intern.buttahtoast.ch
      grafana:
        ingress:
          enable: true
          hosts:
            - grafana.intern.buttahtoast.ch
      prometheus:
        thanosIngress:
          enable: true
          hosts:
            - thanos.intern.buttahtoast.ch
  clusterSelector:
    matchLabels:
      env: prod
      type: infra
